/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/R7Gnxw2HnCN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function ComingSoon() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-background px-4">
      <div className="max-w-md w-full space-y-6 text-center">
        <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Coming Soon</h1>
        <p className="text-muted-foreground md:text-xl">
          We're working hard to bring you something amazing. Sign up to be the first to know when we launch.
        </p>
        <form className="flex gap-2">
          <Input type="email" placeholder="Enter your email" className="flex-1" required />
          <Button type="submit">Notify Me</Button>
        </form>
      </div>
    </div>
  )
}
